# Site wide configuration

title: "WOCATI"
description: "World Conference of Associated Theological Institutions (WOCATI) is a global network to serve, support, and enhance theological education around the World."
logo: /images/international-120x120.png
teaser: teaser.png
locale: en
url: https://www.wocati.org
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from


# Site owner
owner:
  name: WOCATI
  email: hello@wocati.org
  twitter: WOCATI
  google:
    ad-client:
    ad-slot:
  bio: "A global network to serve, support, and enhance theological education around the world."
  avatar: international-160x160.png # 160x160 px image for author byline
  disqus-shortname:

# Front Matter Defaults
defaults:
  - scope:
      path: "wp-content/uploads"
    values:
      image: true
  - scope:
      path: "wp-content/uploads"
    values:
      pdf: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: article
      read_time: true

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
